<a href="https://colab.research.google.com/github/kimgeonhee317/nlpdemystifed-notes/blob/main/notebook/13_Recurrent_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 13_Recurrent Neural Networks

### Import Library

In [1]:
import nltk
import numpy as np
import requests
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import ModelCheckpoint
from nltk.corpus import treebank, brown, conll2000
from sklearn.model_selection import train_test_split
from tensorflow import keras

## Part-of-Speech Tagger with Bidirectional LSTM

In [ ]:
# PoS tagging with LSTM is multiclass classification task for sequence.

# nltk offers free sets for labelled corpora.
# look at https://www.nltk.org/nltk_data
nltk.download('treebank')
nltk.download('brown')
nltk.download('conll2000')

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Unzipping corpora/conll2000.zip.


True

In [ ]:
# Download tagset
nltk.download('universal_tagset')

[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.


True

In [ ]:
# Download all PoS-tagged sentences and place them in one List.
tagged_sentences = treebank.tagged_sents(tagset='universal')+\
                   brown.tagged_sents(tagset='universal')+\
                   conll2000.tagged_sents(tagset='universal')
print(tagged_sentences[0])
print(f"Dataset size: {len(tagged_sentences)}")

[('Pierre', 'NOUN'), ('Vinken', 'NOUN'), (',', '.'), ('61', 'NUM'), ('years', 'NOUN'), ('old', 'ADJ'), (',', '.'), ('will', 'VERB'), ('join', 'VERB'), ('the', 'DET'), ('board', 'NOUN'), ('as', 'ADP'), ('a', 'DET'), ('nonexecutive', 'ADJ'), ('director', 'NOUN'), ('Nov.', 'NOUN'), ('29', 'NUM'), ('.', '.')]
Dataset size: 72202


In [ ]:
sentences, sentence_tags = [], []

for s in tagged_sentences:
  sentence, tags = zip(*s) # multiple numbers of tuple according to sentences
  sentences.append(list(sentence))
  sentence_tags.append(list(tags))

In [ ]:
print(sentences[0])
print(sentence_tags[0])

['Pierre', 'Vinken', ',', '61', 'years', 'old', ',', 'will', 'join', 'the', 'board', 'as', 'a', 'nonexecutive', 'director', 'Nov.', '29', '.']
['NOUN', 'NOUN', '.', 'NUM', 'NOUN', 'ADJ', '.', 'VERB', 'VERB', 'DET', 'NOUN', 'ADP', 'DET', 'ADJ', 'NOUN', 'NOUN', 'NUM', '.']


In [ ]:
print(len(sentences), len(sentence_tags)) # number of sentences

72202 72202


In [ ]:
# split dataset according to the proportion below
train_ratio = 0.75
validation_ratio = 0.15
test_ratio=0.10

# train:test = 0.75:0.25
x_train, x_test, y_train, y_test = train_test_split(sentences, sentence_tags,
                                                     test_size= 1-train_ratio,
                                                     random_state = 317)
# train:val:test = 0.75:0.15:0.10
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test,
                                                test_size = test_ratio/(test_ratio + validation_ratio),
                                                random_state = 317)

In [ ]:
print(len(x_train), len(y_train))
print(len(x_val), len(y_val))
print(len(x_test), len(y_test))

54151 54151
10830 10830
7221 7221


In [ ]:
# Generate wordvectors for our sentenses
# default tokenizer, out-ov-vocabulary token as <OOV>
sentence_tokenizer = keras.preprocessing.text.Tokenizer(oov_token='<OOV')
sentence_tokenizer.fit_on_texts(x_train)
print(f"Vocabulary size: {len(sentence_tokenizer.word_index)}")

Vocabulary size: 52183


In [ ]:
# we need another tokenizer for the tags are also sequences.
tag_tokenizer = keras.preprocessing.text.Tokenizer()
tag_tokenizer.fit_on_texts(y_train)

In [ ]:
print(f"Number of PoS tags: {len(tag_tokenizer.word_index)}\n")
tag_tokenizer.get_config()

Number of PoS tags: 12



{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 54151,
 'word_counts': '{"adv": 51392, "verb": 175631, "adp": 137365, "det": 127600, ".": 143593, "adj": 81110, "noun": 288313, "conj": 35420, "num": 21374, "prt": 31340, "pron": 44737, "x": 6109}',
 'word_docs': '{"conj": 24581, "det": 44815, "verb": 50880, "num": 11905, "adj": 36440, "noun": 51202, "adp": 43937, "adv": 29599, ".": 53331, "prt": 21888, "pron": 26974, "x": 2668}',
 'index_docs': '{"9": 24581, "5": 44815, "2": 50880, "11": 11905, "6": 36440, "1": 51202, "4": 43937, "7": 29599, "3": 53331, "10": 21888, "8": 26974, "12": 2668}',
 'index_word': '{"1": "noun", "2": "verb", "3": ".", "4": "adp", "5": "det", "6": "adj", "7": "adv", "8": "pron", "9": "conj", "10": "prt", "11": "num", "12": "x"}',
 'word_index': '{"noun": 1, "verb": 2, ".": 3, "adp": 4, "det": 5, "adj": 6, "adv": 7, "pron": 8, "conj": 9, "prt": 10, "

In [ ]:
tag_tokenizer.word_index

{'noun': 1,
 'verb': 2,
 '.': 3,
 'adp': 4,
 'det': 5,
 'adj': 6,
 'adv': 7,
 'pron': 8,
 'conj': 9,
 'prt': 10,
 'num': 11,
 'x': 12}

In [ ]:
# convert text to number sequences by fitted tokenizer
x_train_seqs = sentence_tokenizer.texts_to_sequences(x_train)

In [ ]:
print(x_train_seqs[0])
print(x_train[0])

[133, 1921, 19, 8, 13, 1606, 461, 15, 4344, 318, 12, 8, 1922, 28157, 1858, 25, 12287, 28158, 926, 926, 20609, 7, 6603, 6, 20610, 1568, 9, 3198, 39, 13, 145, 6, 1742, 23, 834, 295, 3038, 311, 28159, 32, 28160, 1284, 3, 11, 207, 20609, 1742, 429, 2072, 12288, 15, 4]
['Still', 'existing', 'on', 'a', '``', 'Northern', 'Union', "''", 'telegraph', 'form', 'is', 'a', 'typical', 'peremptory', 'message', 'from', 'Peru', 'grocer', 'J.', 'J.', 'Hapgood', 'to', 'Burton', 'and', "Graves'", 'store', 'in', 'Manchester', '--', '``', 'Get', 'and', 'send', 'by', 'stage', 'four', 'pounds', 'best', 'Porterhouse', 'or', 'serloin', 'stake', ',', 'for', 'Mrs.', 'Hapgood', 'send', 'six', 'sweet', 'oranges', "''", '.']


In [ ]:
y_train_seqs = tag_tokenizer.texts_to_sequences(y_train)

In [ ]:
print(tag_tokenizer.sequences_to_texts([y_train_seqs[0]]))
print(y_train_seqs[0])

['adv verb adp det . adj noun . noun noun verb det adj adj noun adp noun noun noun noun noun adp noun conj noun noun adp noun . . verb conj verb adp noun num noun adj noun conj noun noun . adp noun noun verb num adj noun . .']
[7, 2, 4, 5, 3, 6, 1, 3, 1, 1, 2, 5, 6, 6, 1, 4, 1, 1, 1, 1, 1, 4, 1, 9, 1, 1, 4, 1, 3, 3, 2, 9, 2, 4, 1, 11, 1, 6, 1, 9, 1, 1, 3, 4, 1, 1, 2, 11, 6, 1, 3, 3]


In [ ]:
# Do the same things to valid dataset
x_val_seqs = sentence_tokenizer.texts_to_sequences(x_val)
y_val_seqs = tag_tokenizer.texts_to_sequences(y_val)

In [ ]:
# Even if RNN can handle variable lengthes of sequences, it is musch better for performance to unify the lengthes of each sequences
print(len(max(x_train_seqs, key=len))) # return the length of the longest sequence
MAX_LENGTH = len(max(x_train_seqs, key=len))
print(f"Length of longest input sequence: {MAX_LENGTH}")

271
Length of longest input sequence: 271


In [ ]:
# we can pad every sentences with method "pad_sequences" from keras
x_train_padded = keras.preprocessing.sequence.pad_sequences(x_train_seqs, padding='post',
                                                            maxlen=MAX_LENGTH)


In [ ]:
print(x_train_padded[0])
print(len(x_train_padded[0]))

[  133  1921    19     8    13  1606   461    15  4344   318    12     8
  1922 28157  1858    25 12287 28158   926   926 20609     7  6603     6
 20610  1568     9  3198    39    13   145     6  1742    23   834   295
  3038   311 28159    32 28160  1284     3    11   207 20609  1742   429
  2072 12288    15     4     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0   

In [ ]:
# do the same things to training label
y_train_padded = keras.preprocessing.sequence.pad_sequences(y_train_seqs, padding='post',
                                                           maxlen=MAX_LENGTH)

In [ ]:
x_val_padded = keras.preprocessing.sequence.pad_sequences(x_val_seqs, padding='post', maxlen=MAX_LENGTH)
y_val_padded = keras.preprocessing.sequence.pad_sequences(y_val_seqs, padding='post', maxlen=MAX_LENGTH)

In [ ]:
# As PoS tagging is a multiclass classification task done at each timestep,
# we need to convert every tag for every sentence into one-hot encoding.
y_train_categoricals = keras.utils.to_categorical(y_train_padded)
print(y_train_categoricals[0]) # sequence is now composed of one-hot encodings

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
# one-hot encoding for a single tag in a sequence
print(y_train_categoricals[0][0])

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# we can determind PoS tag from oh-encoding by "look-up" in index_word dictionary from tag_tokenizer
idx = np.argmax(y_train_categoricals[0][0]) # argmax return the index of elememt having maximum value in OHencoding array
print(f"Index: {idx}")
print(f"Tag: {tag_tokenizer.index_word[idx]}")

Index: 7
Tag: adv


In [ ]:
# one hot encoding to val_labels
y_val_categoricals = keras.utils.to_categorical(y_val_padded)

[notes]
At this point, we're ready to build our model. We'll train word embeddings concurrently with our model (though you can use pretrained word vectors as well).

[notes]
1. Ignore padding values :
The embedding layers has *mask_zero* parameter. we added padding in order to make our batches the same size, but we don't want to makd PoS predictions on padding. Setting *mask_zero* to *True* makes the layers following the embedding layer ignore padding values.

2. Return sequences not only one output :
we're using *bidriectional LSTM*. The Bidrectional layer is a wrapper to which we pass an LSTM layer. The first parameter to the LSTM layer is the number of units in the cell. The second parameter, return_sequences, control whether the RNN returns an output for each timestep or only the last output. Since we're doing PoS-tagging, we want an aoutput for each timestep and so *return_sequences* is set to *True*.

In [ ]:
# For the embedding layer. "+1" to account for the padding token.
num_tokens = len(sentence_tokenizer.word_index) + 1 # +1 for padding token
embedding_dim = 128

# For the output layer, The number of classes corresponds to the number of possible tags
num_classes = len(tag_tokenizer.word_index) + 1 # also +1 for padding token

In [ ]:
# we set random_set_seed and kerner_initializer parameter to get same result.
tf.random.set_seed(317)

model = keras.Sequential()

# input layer(embedding layer : each tokens -> embedding_dim )
model.add(layers.Embedding(input_dim = num_tokens,
                           output_dim = embedding_dim,
                           input_length = MAX_LENGTH,
                           mask_zero=True))

# hidden layer (bidrectional)
model.add(layers.Bidirectional(layers.LSTM(128, return_sequences=True,
                                           kernel_initializer=tf.keras.initializers.random_normal(seed=317))))

# output layer for each timestep with softmax activation fucntion
model.add(layers.Dense(num_classes, activation='softmax',
                       kernel_initializer=tf.keras.initializers.random_normal(seed=317)))


model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])



In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 271, 128)          6679552   
                                                                 
 bidirectional (Bidirectiona  (None, 271, 256)         263168    
 l)                                                              
                                                                 
 dense (Dense)               (None, 271, 13)           3341      
                                                                 
Total params: 6,946,061
Trainable params: 6,946,061
Non-trainable params: 0
_________________________________________________________________


[notes] \
1. The embedding layer output has three dimensions
- Batch size : None => we haven't specified it yet
- Sequence length : 217
- Embedding dimension : 128

2. Bidirectional LSTM outputs a vector twice the size of what we specified because its bidirectional. Remember two LSTM output will be concatenated before going to output layer.

3. Output layer also has three dimensions
- Batch size
- Sequence length
- Output dimension : 13 as number of tag classes


In [ ]:
# we put early-stopping for trainig to be stopped when validation loss stops improving.
es_callback = keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)

history = model.fit(x_train_padded, y_train_categoricals, epochs=20,
                    batch_size=256, validation_data=(x_val_padded, y_val_categoricals),
                    callbacks=[es_callback])

Epoch 1/20
212/212 [==============================] - 65s 239ms/step - loss: 0.9598 - accuracy: 0.7057 - val_loss: 0.1617 - val_accuracy: 0.9512
Epoch 2/20
212/212 [==============================] - 25s 117ms/step - loss: 0.1138 - accuracy: 0.9642 - val_loss: 0.1082 - val_accuracy: 0.9642
Epoch 3/20
212/212 [==============================] - 17s 81ms/step - loss: 0.0753 - accuracy: 0.9753 - val_loss: 0.0968 - val_accuracy: 0.9678
Epoch 4/20
212/212 [==============================] - 20s 94ms/step - loss: 0.0595 - accuracy: 0.9803 - val_loss: 0.0944 - val_accuracy: 0.9692
Epoch 5/20
212/212 [==============================] - 14s 66ms/step - loss: 0.0480 - accuracy: 0.9842 - val_loss: 0.0924 - val_accuracy: 0.9703
Epoch 6/20
212/212 [==============================] - 12s 57ms/step - loss: 0.0392 - accuracy: 0.9875 - val_loss: 0.0954 - val_accuracy: 0.9698
Epoch 7/20
212/212 [==============================] - 12s 55ms/step - loss: 0.0322 - accuracy: 0.9898 - val_loss: 0.0995 - val_accurac

In [ ]:
# After our model is trained, go to test data set
# preprocessing(tokenize, pad) it and oh encoding

x_test_seqs = sentence_tokenizer.texts_to_sequences(x_test)
x_test_padded = keras.preprocessing.sequence.pad_sequences(x_test_seqs, padding='post', maxlen=MAX_LENGTH)

y_test_seqs = tag_tokenizer.texts_to_sequences(y_test)
y_test_padded = keras.preprocessing.sequence.pad_sequences(y_test_seqs, padding='post', maxlen=MAX_LENGTH)
y_test_categoricals = keras.utils.to_categorical(y_test_padded)

In [ ]:
model.evaluate(x_test_padded, y_test_categoricals)

226/226 [==============================] - 2s 10ms/step - loss: 0.1052 - accuracy: 0.9688


[0.1051989421248436, 0.9687950611114502]

In [ ]:
# now we can use our models to tag sentences.

samples = [
    "Brown refused to testify.",
    "Brown sofas are on sale",
]

In [ ]:
# develop simple function for doing this task.

def tag_sentences(sentences):
  sentences_seqs = sentence_tokenizer.texts_to_sequences(sentences)
  sentences_padded = keras.preprocessing.sequence.pad_sequences(sentences_seqs,
                                                               maxlen=MAX_LENGTH,
                                                               padding='post')
  # tag_preds is each list of probabilty distribution (softmax)
  tag_preds = model.predict(sentences_padded)

  sentence_tags = []

  # each iteration is one sequence
  for i, preds in enumerate(tag_preds):

    print(preds)
    # seq of most probable ones in sequence
    tags_seq = [np.argmax(p) for p in preds[:len(sentences_seqs[i])]]
    words = [sentence_tokenizer.index_word[w] for w in sentences_seqs[i]]
    tags = [tag_tokenizer.index_word[t] for t in tags_seq]
    sentence_tags.append(list(zip(words, tags)))

  return sentence_tags

In [ ]:
tagged_sample_sentences = tag_sentences(samples)

1/1 [==============================] - 3s 3s/step
[[3.2334467e-06 9.9331737e-01 2.9946794e-04 ... 3.9344709e-04
  1.2747691e-05 2.2187696e-05]
 [1.2938746e-06 3.1313516e-04 9.9806172e-01 ... 1.4160351e-04
  4.5686566e-09 1.3718624e-06]
 [1.2729881e-06 2.0816846e-05 6.1781978e-04 ... 4.8411652e-01
  3.2293276e-05 3.9092065e-06]
 ...
 [7.5027689e-02 8.0436386e-02 7.9266421e-02 ... 7.5670168e-02
  7.5860150e-02 7.5894080e-02]
 [7.5027689e-02 8.0436386e-02 7.9266421e-02 ... 7.5670168e-02
  7.5860150e-02 7.5894080e-02]
 [7.5027689e-02 8.0436386e-02 7.9266421e-02 ... 7.5670168e-02
  7.5860150e-02 7.5894080e-02]]
[[4.2764573e-06 1.5268865e-01 1.3265687e-04 ... 3.5671474e-05
  2.9227600e-04 1.2731762e-05]
 [2.3185294e-08 9.9997950e-01 6.1821049e-07 ... 1.7081586e-06
  1.0583433e-06 1.6246985e-06]
 [4.9634735e-10 3.8132605e-06 9.9999332e-01 ... 1.6310411e-08
  2.7530690e-13 1.3395328e-08]
 ...
 [7.5027689e-02 8.0436386e-02 7.9266421e-02 ... 7.5670168e-02
  7.5860150e-02 7.5894080e-02]
 [7.50276

In [ ]:
print(tagged_sample_sentences[0])
print(tagged_sample_sentences[1])

[('brown', 'noun'), ('refused', 'verb'), ('to', 'adp'), ('testify', 'verb')]
[('brown', 'adj'), ('sofas', 'noun'), ('are', 'verb'), ('on', 'adp'), ('sale', 'noun')]


It's just one way of buidling a PoS tagger, these days' PoS tagger is much more sophisticated models in which transfomer is used.

## Language Modelling With Stacked LSTMs

In [9]:
# download sample corpus
art_of_war = requests.get('https://raw.githubusercontent.com/nitinpunjabi/nlp-demystified/main/datasets/art_of_war.txt')\
                     .text

art_of_war[:300]

'1. Sun Tzŭ said: The art of war is of vital importance to the State.\n\n2. It is a matter of life and death, a road either to safety or to\nruin. Hence it is a subject of inquiry which can on no account be\nneglected.\n\n3. The art of war, then, is governed by five constant factors, to be\ntaken into accou'

[notes]\
We will build character-based language model(opposed to word-based)

Character-level models have the advantage of:
1. Smaller prediction space (smaller character than words.. in english obviously)
2. More resilient to the out-of-vocabulary(OOV) problem. and better able to learn lower mechanics of language (including punctuation)

On the other hand, character-level models need to learn a sequence of charcters to "make sense" of a word (e.g. the sequence of "c", "a", "t" to identify "cat" as a pattern) which can be inefficient and result in lower performance.

RNNs can process any kind of sequence so what's shown here can easily be applied at the word level. When we cover transformers, there is an alterniative approaches called subword tokenization which is the moddle-ground between these two approaches.


In [3]:
tokenizer = keras.preprocessing.text.Tokenizer(char_level = True)

In [4]:
tokenizer.fit_on_texts([art_of_war])

In [5]:
tokenizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': True,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"1": 179, ".": 896, " ": 9794, "s": 3081, "u": 1467, "n": 3565, "t": 4398, "z": 20, "\\u016d": 13, "a": 3475, "i": 3573, "d": 1681, ":": 48, "h": 2558, "e": 5837, "r": 2776, "o": 3548, "f": 1238, "w": 981, "v": 478, "l": 1722, "m": 1201, "p": 769, "c": 1390, "\\n": 1443, "2": 127, ",": 634, "y": 1055, "b": 708, "j": 23, "q": 55, "g": 1007, "3": 87, "k": 345, "\\u2019": 57, "4": 66, "(": 59, ")": 59, ";": 168, "5": 58, "6": 51, "_": 62, "7": 39, "8": 36, "9": 34, "0": 38, "x": 49, "\\u2014": 16, "?": 8, "!": 8, "-": 57, "\\u201c": 3, "\\u201d": 3, "\\u0153": 7, "\\u00fc": 3, "\\u2018": 1}',
 'word_docs': '{"e": 1, "\\u016d": 1, "6": 1, "j": 1, "w": 1, "c": 1, "y": 1, "7": 1, "5": 1, "\\u2018": 1, "p": 1, "g": 1, "2": 1, "k": 1, " ": 1, "b": 1, "0": 1, "m": 1, "\\u201c": 1, "s": 1, "4": 1, "9": 1, "?": 1, "

In [7]:
print(f"Tokenizer \"Vocabulary\" size : {len(tokenizer.word_index)}")

Tokenizer "Vocabulary" size : 56


In [12]:
seq = tokenizer.texts_to_sequences([art_of_war])[0] # first sequence

In [13]:
print(f"Text length: {len(seq)}")

Text length: 61054


In [14]:
# Sanity check.
tokenizer.sequences_to_texts([seq[:10]])

['1 .   s u n   t z ŭ']

In [15]:
# we'll gonna use "Tensorflow Data API" which makes it easy to build preprocessing pipelines by chaining operations together
# To use this, we need to converted our vectorized courpus into Dataset object (from_tensor_slices)
slices = tf.data.Dataset.from_tensor_slices(seq)
type(slices)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [16]:
list(slices.take(10))

[<tf.Tensor: shape=(), dtype=int32, numpy=27>,
 <tf.Tensor: shape=(), dtype=int32, numpy=21>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=13>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=47>,
 <tf.Tensor: shape=(), dtype=int32, numpy=49>]

In [17]:
seq[:10]

[27, 21, 1, 8, 13, 5, 1, 3, 47, 49]

In [19]:
# we'll use window method. window size will be 100. Dataset of 1000 willbe sequence of 10 datasets, each containing 100 elements
# Here, we create window "input_timesteps + 1" which is for target/label for each training example.
# Shift to 1, window shift tactics.
# Drop_remainder to True which ensure All windows contain exactly N elements. i.e. once input contians fewer than N, it dropped.
input_timesteps = 100
window_size = input_timesteps + 1
windows = slices.window(window_size, shift=1, drop_remainder=True)

In [20]:
for w in windows.take(3):
  arr = list(w.as_numpy_iterator())
  print(len(arr), arr)

101 [27, 21, 1, 8, 13, 5, 1, 3, 47, 49, 1, 8, 7, 4, 12, 41, 1, 3, 10, 2, 1, 7, 9, 3, 1, 6, 16, 1, 20, 7, 9, 1, 4, 8, 1, 6, 16, 1, 25, 4, 3, 7, 11, 1, 4, 17, 22, 6, 9, 3, 7, 5, 15, 2, 1, 3, 6, 1, 3, 10, 2, 1, 8, 3, 7, 3, 2, 21, 14, 14, 29, 21, 1, 4, 3, 1, 4, 8, 1, 7, 1, 17, 7, 3, 3, 2, 9, 1, 6, 16, 1, 11, 4, 16, 2, 1, 7, 5, 12, 1, 12]
101 [21, 1, 8, 13, 5, 1, 3, 47, 49, 1, 8, 7, 4, 12, 41, 1, 3, 10, 2, 1, 7, 9, 3, 1, 6, 16, 1, 20, 7, 9, 1, 4, 8, 1, 6, 16, 1, 25, 4, 3, 7, 11, 1, 4, 17, 22, 6, 9, 3, 7, 5, 15, 2, 1, 3, 6, 1, 3, 10, 2, 1, 8, 3, 7, 3, 2, 21, 14, 14, 29, 21, 1, 4, 3, 1, 4, 8, 1, 7, 1, 17, 7, 3, 3, 2, 9, 1, 6, 16, 1, 11, 4, 16, 2, 1, 7, 5, 12, 1, 12, 2]
101 [1, 8, 13, 5, 1, 3, 47, 49, 1, 8, 7, 4, 12, 41, 1, 3, 10, 2, 1, 7, 9, 3, 1, 6, 16, 1, 20, 7, 9, 1, 4, 8, 1, 6, 16, 1, 25, 4, 3, 7, 11, 1, 4, 17, 22, 6, 9, 3, 7, 5, 15, 2, 1, 3, 6, 1, 3, 10, 2, 1, 8, 3, 7, 3, 2, 21, 14, 14, 29, 21, 1, 4, 3, 1, 4, 8, 1, 7, 1, 17, 7, 3, 3, 2, 9, 1, 6, 16, 1, 11, 4, 16, 2, 1, 7, 5, 12, 1, 12, 2

In [21]:
# window method returns a nested dataset of datasets
print(windows, '\n')

for w in windows.take(2):
  print(w)

<_WindowDataset element_spec=DatasetSpec(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorShape([]))> 

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>


In [24]:
# Our model only accept tensors. We need to extract tensors from each window using 'flat_map'
dataset = windows.flat_map(lambda window: window.batch(window_size))

In [26]:
# Now we have single dataset of tensors, where each tensor is "input_timesteps+1" long and shifted by 1.
for d in dataset.take(2):
  print(d)

tf.Tensor(
[27 21  1  8 13  5  1  3 47 49  1  8  7  4 12 41  1  3 10  2  1  7  9  3
  1  6 16  1 20  7  9  1  4  8  1  6 16  1 25  4  3  7 11  1  4 17 22  6
  9  3  7  5 15  2  1  3  6  1  3 10  2  1  8  3  7  3  2 21 14 14 29 21
  1  4  3  1  4  8  1  7  1 17  7  3  3  2  9  1  6 16  1 11  4 16  2  1
  7  5 12  1 12], shape=(101,), dtype=int32)
tf.Tensor(
[21  1  8 13  5  1  3 47 49  1  8  7  4 12 41  1  3 10  2  1  7  9  3  1
  6 16  1 20  7  9  1  4  8  1  6 16  1 25  4  3  7 11  1  4 17 22  6  9
  3  7  5 15  2  1  3  6  1  3 10  2  1  8  3  7  3  2 21 14 14 29 21  1
  4  3  1  4  8  1  7  1 17  7  3  3  2  9  1  6 16  1 11  4 16  2  1  7
  5 12  1 12  2], shape=(101,), dtype=int32)


In [27]:
# Create batches from our data set. shuffle and create!
batch_size = 32
batches = dataset.shuffle(10000).batch(batch_size)

In [28]:
for b in batches.take(2):
  print(b)

tf.Tensor(
[[ 2  1  6 ... 17 18  1]
 [18  4  5 ... 10  4  8]
 [ 1 12  4 ...  2  9  4]
 ...
 [ 2  5 19 ... 36  8  1]
 [ 1  3  6 ... 10  4 19]
 [13  8  7 ...  1 10  6]], shape=(32, 101), dtype=int32)
tf.Tensor(
[[ 1  4  8 ...  4 15  2]
 [17  7  5 ...  2  1 10]
 [ 3  7  5 ... 15  3  6]
 ...
 [13  8  3 ... 24  1 20]
 [ 9  4  8 ...  1  6 16]
 [ 3  9  2 ...  1  4  5]], shape=(32, 101), dtype=int32)


[notes]\
We talked about _Teacher Forcing_
1. At each timestep during training, the output is compared to a label
2. At the next timestep, rather than feeding the model the previous output, we feed it the next character of input sequence(i.e. what model should've outputted - label!)

This is why each sequence is of size _input_timestep+1_. Each sequence is now going to be separated into Two sequences. The first sequence will be training input and will be length input_timepsteps. The second sequence will be the label/target and will consist of all the sequence elements shifted by 1.

So if processed sequence is "she swam in the lake", then:
+ the input will be "she swam in the lak" (drop last char)
+ the target/label will be "he swam in the lake" (drop first char)


In [34]:
# x-y paired bathces
xy_batches = batches.map(lambda batch: (batch[:, :-1], batch[:, 1:]))

In [33]:
for b in xy_batches.take(1):
  print(b)

(<tf.Tensor: shape=(32, 100), dtype=int32, numpy=
array([[ 5,  8,  1, ...,  6,  5,  8],
       [ 1,  9, 13, ..., 26,  1, 10],
       [ 7, 11,  1, ..., 21,  1, 20],
       ...,
       [ 6,  5,  8, ...,  4,  6,  5],
       [14,  5,  2, ..., 13,  5,  3],
       [25,  7,  5, ..., 14, 33, 35]], dtype=int32)>, <tf.Tensor: shape=(32, 100), dtype=int32, numpy=
array([[ 8,  1,  4, ...,  5,  8,  1],
       [ 9, 13, 11, ...,  1, 10,  4],
       [11,  1,  6, ...,  1, 20, 10],
       ...,
       [ 5,  8,  1, ...,  6,  5,  8],
       [ 5,  2, 19, ...,  5,  3,  1],
       [ 7,  5,  3, ..., 33, 35, 34]], dtype=int32)>)


In [35]:
# For greater clarity.